
console.log('hai ganteng!)
console.log('hai ganteng!)
console.log('hai ganteng!)
console.log('hai ganteng!)
console.log('hai ganteng!)
console.log('hai ganteng!)
console.log('hai ganteng!)
console.log('hai ganteng!)
console.log('hai ganteng!)
